### ISSUE TITLE
download failed from fox's mm

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/Zeetaa-Tweaks#1]
change branches name from `main` to `master`, overwise your module cannot download from Fox's MM

**Comment by NotZeetaa** [comment]
> change branches name from `main` to `master`, overwise your module cannot download from Fox's MM

Oh Ok thx for the info

**Comment by NotZeetaa** [comment]
> change branches name from `main` to `master`, overwise your module cannot download from Fox's MM

Done thx :)

**Comment by HuskyDG** [comment]
Also tks for the nice module
